version: '3.6'
services:

  php-fpm:
    build: docker/php-fpm
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./:/www"
    environment:
      - DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}
      - DOCKER_XDEBUG=${DOCKER_XDEBUG}
      - DOCKER_SUPERVISOR=${DOCKER_SUPERVISOR}
      - DOCKER_CRON=${DOCKER_CRON}
    networks:
      - three

  nginx:
    image: nginx:1.16-alpine
    depends_on:
      - php-fpm
    ports:
      - "8200:80"
    volumes:
      - "./:/www"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - three

  db:
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - ./docker/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOCKER_DATABASE}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
    ports:
      - "8201:5432"
    networks:
      - three

  node-watch:
    image: node:12.7-alpine
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    networks:
      - three

  node:
      image: node:12.7-alpine
      volumes:
        - "./:/app"
      working_dir: "/app"
      networks:
        - three

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8203:8025"
    depends_on:
      - php-fpm
    networks:
      - three

networks:
  three:
    driver: bridge
